export const CONVERSATION_ERROR_MESSAGES = {
  CONVERSATION_NOT_FOUND: '对话不存在',
  CONVERSATION_CREATE_FAILED: '对话创建失败',
  CONVERSATION_UPDATE_FAILED: '对话更新失败',
  CONVERSATION_DELETE_FAILED: '对话删除失败',
  CONVERSATION_LIST_FAILED: '对话列表获取失败',
  INVALID_CONVERSATION_DATA: '对话数据无效',
  CONVERSATION_ALREADY_EXISTS: '对话已存在',
  CONVERSATION_ACCESS_DENIED: '无权访问此对话',
  CONVERSATION_VALIDATION_FAILED: '对话验证失败',
  MESSAGE_SEND_FAILED: '消息发送失败',
  MESSAGE_NOT_FOUND: '消息不存在',
  INVALID_MESSAGE_TYPE: '无效的消息类型',
} as const;

export const CONVERSATION_ERROR_CODES = {
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_CREATE_FAILED: 'CONVERSATION_CREATE_FAILED',
  CONVERSATION_UPDATE_FAILED: 'CONVERSATION_UPDATE_FAILED',
  CONVERSATION_DELETE_FAILED: 'CONVERSATION_DELETE_FAILED',
  CONVERSATION_LIST_FAILED: 'CONVERSATION_LIST_FAILED',
  INVALID_CONVERSATION_DATA: 'INVALID_CONVERSATION_DATA',
  CONVERSATION_ALREADY_EXISTS: 'CONVERSATION_ALREADY_EXISTS',
  CONVERSATION_ACCESS_DENIED: 'CONVERSATION_ACCESS_DENIED',
  CONVERSATION_VALIDATION_FAILED: 'CONVERSATION_VALIDATION_FAILED',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  INVALID_MESSAGE_TYPE: 'INVALID_MESSAGE_TYPE',
} as const;
