export const CONVERSATION_ERRORS = {
  NOT_FOUND: 'CONVERSATION.NOT_FOUND',
  UNAUTHORIZED: 'CONVERSATION.UNAUTHORIZED',
  INVALID_MESSAGE: 'CONVERSATION.INVALID_MESSAGE',
  TOO_MANY_MESSAGES: 'CONVERSATION.TOO_MANY_MESSAGES',
  LIMIT_EXCEEDED: 'CONVERSATION.LIMIT_EXCEEDED',
} as const;

export const MESSAGE_ROLES = {
  USER: 'user',
  ASSISTANT: 'assistant',
  SYSTEM: 'system',
} as const;

export const MESSAGE_ROLE_NAMES = {
  [MESSAGE_ROLES.USER]: '用户',
  [MESSAGE_ROLES.ASSISTANT]: '助手',
  [MESSAGE_ROLES.SYSTEM]: '系统',
} as const;

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
} as const;

export const CONVERSATION_STATUS = {
  ACTIVE: 1,
  ARCHIVED: 0,
} as const;

export const CONVERSATION_STATUS_NAMES = {
  [CONVERSATION_STATUS.ACTIVE]: '活跃',
  [CONVERSATION_STATUS.ARCHIVED]: '已归档',
} as const;

export const CONVERSATION_LIMITS = {
  MAX_CONVERSATIONS_PER_USER: 50,
  MAX_MESSAGES_PER_MINUTE: 10,
  MAX_MESSAGE_LENGTH: 2000,
} as const;
